[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cosine_sim_engine"
version = "0.1.0"
description = "Cosine similarity engine for disease classification."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"

authors = [
    { name = "Luis Mendez" }
]

dependencies = [
    "numpy>=2.0",
    "pandas>=2.0",
    "pytest"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
cosine_sim_engine = ["data/*.csv"]

[project.urls]
Homepage = "https://github.com/Mendez016/Disease-Diagnosis-Engine-V1/tree/main"